#pragma once
// Auto-generated by obj2model.py - DO NOT EDIT.
// Source: character.json
// Scale:  0.002089   Centred: True

#include "controllers/AnimationController.h"

enum Model_character {
    MODEL_CHARACTER_ARMATUREACTION = 0,
};

enum Model_character_TexSlot {
    MODEL_CHARACTER_TEX_DISS_00 = 0,
    MODEL_CHARACTER_TEX_DISS_01 = 1,
    MODEL_CHARACTER_TEX_DISS_02 = 2,
    MODEL_CHARACTER_TEX_DISS_03 = 3,
    MODEL_CHARACTER_TEX_DISS_04 = 4,
    MODEL_CHARACTER_TEX_COUNT = 5
};

// Call after AnimationController::loadModel() to upload textures.
// Pass bitmaps in the same order as Model_character_TexSlot.
inline void character_loadTextures(
    AnimationController& ctrl,
    const unsigned int* bitmaps[MODEL_CHARACTER_TEX_COUNT])
{
    static const int  widths [5] = { 64, 64, 64, 64, 64 };
    static const int  heights[5] = { 64, 64, 64, 64, 32 };
    static const bool isRGBA [5] = { false, false, false, false, false };
    ctrl.loadTextures(MODEL_CHARACTER_TEX_COUNT,
                      bitmaps, widths, heights, isRGBA);
}
