// Auto-generated by obj2offsets.py — do not edit by hand
// OBJ:  character_32x32.obj
// MAP:  character_0_0_32_32.png
//
// Vertex bounds:  X [-0.097034 → 0.097034]  Z [-0.031250 → 0.031250]
// World size:     0.194069 × 0.062500
// Tile grid:      32 × 32

#ifndef CHARACTER_OFFSETS_H
#define CHARACTER_OFFSETS_H

#define TILE_SIZE      0.006065f  // world_width / tile_cols
#define WORLD_OFFSET_X 0.097034f  // -minX
#define WORLD_OFFSET_Z 0.031250f  // -minZ

// Debug print — paste into your game loop to verify:
// iprintf("\x1b[21;0Htile(x,z): %d, %d",
//     (int)((charPos.x + WORLD_OFFSET_X) / TILE_SIZE),
//     (int)((charPos.z + WORLD_OFFSET_Z) / TILE_SIZE));

#endif // CHARACTER_OFFSETS_H
