#include "IwatodaiStreetsView.h"
#include "core/globals.h"
#include "math.h"
#include <malloc.h>
#include <nds.h>
#include <stdio.h>

// map
#include "maps/iwatodai_streets.h"
// environment
#include "environments/iwatodai_streets.h"
// street textures (generated by grit)
#include "f007_009_02.h"
#include "f007_009_03.h"
#include "f007_009_04.h"
#include "f007_009_05.h"
#include "f007_009_07.h"
#include "f007_009_08.h"
#include "f007_009_09.h"
#include "f007_009_10.h"
#include "f007_009_11.h"
#include "f007_009_12.h"
#include "f007_009_13.h"
#include "f007_009_16.h"
#include "f007_009_17.h"
#include "f007_009_18.h"
#include "f007_009_22.h"
#include "f007_009_24.h"
#include "f007_009_25.h"
#include "f007_009_27.h"
#include "f007_009_28.h"
#include "f007_009_29.h"
#include "f007_009_30.h"
#include "f007_009_32.h"
#include "f007_009_33.h"
#include "f007_009_infloor.h"
#include "f007_009_wood01.h"
// model
#include "character.h"
#include "models/character.h"

int streetsCharacterTextureId;
iwatodai_streets_Environment iwatodaiStreetsEnv;

void IwatodaiStreetsView::init()
{
    videoSetMode(MODE_0_3D);
    videoSetModeSub(MODE_0_2D);

    vramSetBankA(VRAM_A_TEXTURE);
    vramSetBankB(VRAM_B_TEXTURE);
    vramSetBankC(VRAM_C_SUB_BG);
    vramSetBankD(VRAM_D_SUB_SPRITE);
    bgExtPaletteEnableSub();

    glInit();
    glEnable(GL_ANTIALIAS);
    glEnable(GL_TEXTURE_2D);

    glClearColor(0, 0, 0, 31);
    glClearPolyID(63);
    glClearDepth(0x7FFF);

    glViewport(0, 0, 255, 191);

    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    gluPerspective(55, 256.0 / 192.0, 0.1, 40);

    glPolyFmt(POLY_ALPHA(31) | POLY_CULL_BACK);
    glColor3b(255, 255, 255);

    // sub screen console
    bgSharedSlot = bgInitSub(0, BgType_Text8bpp, BgSize_T_256x256, 0, 1);
    bgMenuHUD = bgInitSub(2, BgType_Text8bpp, BgSize_T_256x256, 10, 3);
    dmaFillHalfWords(0, bgGetMapPtr(bgSharedSlot), 2048);
    dmaFillHalfWords(0, bgGetMapPtr(bgMenuHUD), 2048);

    consoleInit(&console, 1, BgType_Text4bpp, BgSize_T_256x256, 4, 5, false, true);
    consoleSelect(&console);

    bgSetPriority(console.bgId, 0);
    bgSetPriority(bgSharedSlot, 1);
    bgSetPriority(bgMenuHUD, 2);
    bgUpdate();

    // setup menuHUD
    // uses VRAM bank I for sprite extended palettes, VRAM H for bg palettes
    menuHUDCmpt.loadHUD();

    playerCtrl = new CharacterController(IWATODAI_STREETS_MAP_WIDTH,
                                         IWATODAI_STREETS_MAP_HEIGHT,
                                         &iwatodai_streets_map[0][0],
                                         tileSize,
                                         worldOffsetX,
                                         worldOffsetZ,
                                         characterSize,
                                         speed,
                                         angleIncrement,
                                         distance,
                                         lookAhead,
                                         angle,
                                         height,
                                         characterTranslate,
                                         characterFacingAngle,
                                        true);

    // setup music
    musicCtrl.init((fatBasePath + "/music/changing_seasons.pcm").c_str(), 0.0f, -1.0f);

    // setup character model
    characterAnimationCtrl.loadModel((fatBasePath + "models/character.bin").c_str());
    character_loadTextures(characterAnimationCtrl, bitmapsCharacter);

    // setup environment model
    const unsigned int* bitmaps[IWATODAI_STREETS_TEX_COUNT] = {
        f007_009_07Bitmap,      f007_009_16Bitmap, f007_009_30Bitmap, f007_009_25Bitmap, f007_009_08Bitmap,
        f007_009_05Bitmap,      f007_009_02Bitmap, f007_009_04Bitmap, f007_009_28Bitmap, f007_009_24Bitmap,
        f007_009_infloorBitmap, f007_009_09Bitmap, f007_009_11Bitmap, f007_009_10Bitmap, f007_009_13Bitmap,
        f007_009_12Bitmap,      f007_009_17Bitmap, f007_009_18Bitmap, f007_009_32Bitmap, f007_009_33Bitmap,
        f007_009_29Bitmap,      f007_009_27Bitmap, f007_009_22Bitmap, f007_009_03Bitmap, f007_009_wood01Bitmap,
    };
    iwatodaiStreetsEnv.load((fatBasePath + "environments/iwatodai_streets.bin").c_str(), bitmaps);
    totalPolyCount = iwatodaiStreetsEnv.getPolyCount();

    // pause menu
    pauseMenuCmpt.init(bgSharedSlot, &isPauseMenuActive);
}

ViewState IwatodaiStreetsView::update()
{
    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();
    bgUpdate();
    oamUpdate(&oamSub);

    scanKeys();
    u32 keys = keysHeld();
    u32 pressed = keysDown();

    if (pressed & KEY_START)
    {
        isPauseMenuActive = !isPauseMenuActive;
    }

    // touch input
    if (pressed & KEY_TOUCH)
    {
        touchRead(&touch);
        if (menuHUDCmpt.isMenuTouchArea(&touch))
        {
            isPauseMenuActive = true;
        }
    }

    // draw menuHUD
    if (!isPauseMenuActive)
    {
        menuHUDCmpt.drawHUD(&bgMenuHUD);
        bgShow(bgMenuHUD);
    }
    // hide menuHUD if pauseMenu is active
    else
    {
        bgHide(bgMenuHUD);
        oamClear(&oamSub, 0, 0);
    }

    if (isPauseMenuActive)
    {
        ViewState menuResult = pauseMenuCmpt.update(pressed);
        if (menuResult != ViewState::KEEP_CURRENT)
        {
            musicCtrl.pause();
            return menuResult;
        }
    }
    else
    {
        consoleClear();
        bgHide(bgSharedSlot);

        camPos = playerCtrl->update(keys);

        if (playerCtrl->isTileAt() == TileType::PREV_SCENE)
        {
            musicCtrl.pause();
            return ViewState::IWATODAI_DORM;
        }

        gluLookAt(camPos.cameraX,
                  camPos.cameraY + 0.3f,
                  camPos.cameraZ,
                  camPos.targetX,
                  camPos.targetY,
                  camPos.targetZ,
                  camPos.upX,
                  camPos.upY,
                  camPos.upZ);

        glPushMatrix();
        iwatodaiStreetsEnv.draw();
        glPopMatrix(1);

        glPushMatrix();
        characterPosition charPos = playerCtrl->isCharacterAt();
        glTranslatef(charPos.x, charPos.y, charPos.z);
        glRotatef(charPos.facingAngle, 0.0f, 1.0f, 0.0f);
        characterAnimationCtrl.render();
        glPopMatrix(1);

        glFlush(0);

        // print coordinates (64x64 area from 0,0 to 64,64)
        if (enableDebugPrint)
        {
            iprintf("\x1b[19;0H\033[31mTouch x = %04X, %04X\n", touch.rawx, touch.px);
            iprintf("\x1b[20;0H\033[31mTouch y = %04X, %04X\n", touch.rawy, touch.py);
            iprintf("\x1b[21;0H\033[31mtile(x,z): %d, %d",
                    (int)((charPos.x + worldOffsetX) / tileSize),
                    (int)((charPos.z + worldOffsetZ) / tileSize));
            iprintf("\x1b[22;0H\033[31mtranslate(x,z): %d, %d", (int)(charPos.x * 100), (int)(charPos.z * 100));
            iprintf(
                "\x1b[23;0H\033[31mangle(w,c): %d, %d", (int)(charPos.angle * 100), (int)(charPos.facingAngle * 100));
        }
    }

    musicCtrl.update();
    characterAnimationCtrl.update();

    return ViewState::KEEP_CURRENT;
}

void IwatodaiStreetsView::cleanup()
{
    BaseView::cleanup();

    iwatodaiStreetsEnv.cleanup();
    glDeleteTextures(1, &streetsCharacterTextureId);
    dmaFillHalfWords(0, bgGetMapPtr(bgSharedSlot), 2048);

    delete playerCtrl;
    playerCtrl = nullptr;
}
