#pragma once
// Auto-generated by obj2environment.py
// Source: iwatodai_dorm_floor_1.obj
// Scale: 0.001410  Centred: True  max_tex_size: 64
// DO NOT EDIT - regenerate from source.

#include <nds.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// World bounds
#define IWATODAI_DORM_FLOOR_1_WORLD_OFFSET_X 1.765507f
#define IWATODAI_DORM_FLOOR_1_WORLD_OFFSET_Z 2.750000f
#define IWATODAI_DORM_FLOOR_1_WORLD_WIDTH    3.531014f
#define IWATODAI_DORM_FLOOR_1_WORLD_DEPTH    5.500000f

enum iwatodai_dorm_floor_1_TexSlot {
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL01 = 0,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL02 = 1,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL03 = 2,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002DOOR02 = 3,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002KZR01 = 4,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002KZR02 = 5,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ01 = 6,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ04 = 7,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ07 = 8,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ11 = 9,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL04 = 10,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL05 = 11,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL06 = 12,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ10 = 13,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002STEP01 = 14,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002STEP02 = 15,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002KZR03 = 16,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002KZR04 = 17,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002DOOR01 = 18,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ03 = 19,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002SHADOW01 = 20,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ09 = 21,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002BOLT01 = 22,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002GLOW02 = 23,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002FLOOR01 = 24,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002FLOOR02 = 25,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002FLOOR03 = 26,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ02 = 27,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ05 = 28,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ14 = 29,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ15 = 30,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002BOLT02 = 31,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002BOLT03 = 32,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ12 = 33,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ13 = 34,
    IWATODAI_DORM_FLOOR_1_TEX_COUNT = 35
};

struct iwatodai_dorm_floor_1_BillboardData {
    v16 x, y, z;
    v16 halfWidth, halfHeight;
    int texSlot;
    short u0, v0, u1, v1;
};

class iwatodai_dorm_floor_1_Environment {
public:
    u32* displayLists[35];
    u32  dlSizes[35];
    int  textureIDs[35];

    static const int BILLBOARD_COUNT = 0;
    const iwatodai_dorm_floor_1_BillboardData* BILLBOARDS = NULL;

    iwatodai_dorm_floor_1_Environment() {
        for (int i = 0; i < 35; i++) {
            displayLists[i] = NULL; dlSizes[i] = 0; textureIDs[i] = 0;
        }
    }

    bool load(const char* filepath, const unsigned int* bitmaps[35]) {
        FILE* file = fopen(filepath, "rb");
        if (!file) return false;

        char magic[4];
        fread(magic, 1, 4, file);
        if (magic[0]!='E'||magic[1]!='N'||magic[2]!='V'||magic[3]!='1') {
            fclose(file); return false;
        }

        u32 groupCount;
        fread(&groupCount, sizeof(u32), 1, file);
        if (groupCount != 35) { fclose(file); return false; }

        for (u32 i = 0; i < groupCount; i++) {
            fread(&dlSizes[i], sizeof(u32), 1, file);
            displayLists[i] = (u32*)malloc((dlSizes[i] + 1) * sizeof(u32));
            displayLists[i][0] = dlSizes[i];
            if (dlSizes[i] > 0)
                fread(&displayLists[i][1], sizeof(u32), dlSizes[i], file);
        }
        fclose(file);

        if (bitmaps[0]) {
            glGenTextures(1, &textureIDs[0]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[0]);
        }
        if (bitmaps[1]) {
            glGenTextures(1, &textureIDs[1]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[1]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[1]);
        }
        if (bitmaps[2]) {
            glGenTextures(1, &textureIDs[2]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[2]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_32, TEXTURE_SIZE_32, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[2]);
        }
        if (bitmaps[3]) {
            glGenTextures(1, &textureIDs[3]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[3]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[3]);
        }
        if (bitmaps[4]) {
            glGenTextures(1, &textureIDs[4]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[4]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[4]);
        }
        if (bitmaps[5]) {
            glGenTextures(1, &textureIDs[5]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[5]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[5]);
        }
        if (bitmaps[6]) {
            glGenTextures(1, &textureIDs[6]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[6]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[6]);
        }
        if (bitmaps[7]) {
            glGenTextures(1, &textureIDs[7]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[7]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[7]);
        }
        if (bitmaps[8]) {
            glGenTextures(1, &textureIDs[8]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[8]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[8]);
        }
        if (bitmaps[9]) {
            glGenTextures(1, &textureIDs[9]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[9]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[9]);
        }
        if (bitmaps[10]) {
            glGenTextures(1, &textureIDs[10]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[10]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_32, TEXTURE_SIZE_32, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[10]);
        }
        if (bitmaps[11]) {
            glGenTextures(1, &textureIDs[11]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[11]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[11]);
        }
        if (bitmaps[12]) {
            glGenTextures(1, &textureIDs[12]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[12]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_32, TEXTURE_SIZE_32, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[12]);
        }
        if (bitmaps[13]) {
            glGenTextures(1, &textureIDs[13]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[13]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[13]);
        }
        if (bitmaps[14]) {
            glGenTextures(1, &textureIDs[14]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[14]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[14]);
        }
        if (bitmaps[15]) {
            glGenTextures(1, &textureIDs[15]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[15]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_32, TEXTURE_SIZE_32, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[15]);
        }
        if (bitmaps[16]) {
            glGenTextures(1, &textureIDs[16]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[16]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[16]);
        }
        if (bitmaps[17]) {
            glGenTextures(1, &textureIDs[17]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[17]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[17]);
        }
        if (bitmaps[18]) {
            glGenTextures(1, &textureIDs[18]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[18]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[18]);
        }
        if (bitmaps[19]) {
            glGenTextures(1, &textureIDs[19]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[19]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[19]);
        }
        if (bitmaps[20]) {
            glGenTextures(1, &textureIDs[20]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[20]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[20]);
        }
        if (bitmaps[21]) {
            glGenTextures(1, &textureIDs[21]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[21]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[21]);
        }
        if (bitmaps[22]) {
            glGenTextures(1, &textureIDs[22]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[22]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[22]);
        }
        if (bitmaps[23]) {
            glGenTextures(1, &textureIDs[23]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[23]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[23]);
        }
        if (bitmaps[24]) {
            glGenTextures(1, &textureIDs[24]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[24]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[24]);
        }
        if (bitmaps[25]) {
            glGenTextures(1, &textureIDs[25]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[25]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[25]);
        }
        if (bitmaps[26]) {
            glGenTextures(1, &textureIDs[26]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[26]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[26]);
        }
        if (bitmaps[27]) {
            glGenTextures(1, &textureIDs[27]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[27]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[27]);
        }
        if (bitmaps[28]) {
            glGenTextures(1, &textureIDs[28]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[28]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[28]);
        }
        if (bitmaps[29]) {
            glGenTextures(1, &textureIDs[29]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[29]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[29]);
        }
        if (bitmaps[30]) {
            glGenTextures(1, &textureIDs[30]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[30]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[30]);
        }
        if (bitmaps[31]) {
            glGenTextures(1, &textureIDs[31]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[31]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[31]);
        }
        if (bitmaps[32]) {
            glGenTextures(1, &textureIDs[32]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[32]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_32, TEXTURE_SIZE_32, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[32]);
        }
        if (bitmaps[33]) {
            glGenTextures(1, &textureIDs[33]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[33]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_32, TEXTURE_SIZE_32, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[33]);
        }
        if (bitmaps[34]) {
            glGenTextures(1, &textureIDs[34]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[34]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[34]);
        }
        return true;
    }

    int getPolyCount() const {
        int total = 0;
        for (int i = 0; i < 35; i++) {
            if (dlSizes[i] > 0) {
                const u32* dl = &displayLists[i][1];
                for (u32 j = 0; j < dlSizes[i]; j++) {
                    u32 w = dl[j];
                    for (int b = 0; b < 4; b++) {
                        if (((w >> (b * 8)) & 0xFF) == 0x40) total++;
                    }
                }
            }
        }
        return total;
    }

    void draw() {
        glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
        if (displayLists[0]) glCallList(displayLists[0]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[1]);
        if (displayLists[1]) glCallList(displayLists[1]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[2]);
        if (displayLists[2]) glCallList(displayLists[2]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[3]);
        if (displayLists[3]) glCallList(displayLists[3]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[4]);
        if (displayLists[4]) glCallList(displayLists[4]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[5]);
        if (displayLists[5]) glCallList(displayLists[5]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[6]);
        if (displayLists[6]) glCallList(displayLists[6]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[7]);
        if (displayLists[7]) glCallList(displayLists[7]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[8]);
        if (displayLists[8]) glCallList(displayLists[8]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[9]);
        if (displayLists[9]) glCallList(displayLists[9]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[10]);
        if (displayLists[10]) glCallList(displayLists[10]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[11]);
        if (displayLists[11]) glCallList(displayLists[11]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[12]);
        if (displayLists[12]) glCallList(displayLists[12]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[13]);
        if (displayLists[13]) glCallList(displayLists[13]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[14]);
        if (displayLists[14]) glCallList(displayLists[14]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[15]);
        if (displayLists[15]) glCallList(displayLists[15]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[16]);
        if (displayLists[16]) glCallList(displayLists[16]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[17]);
        if (displayLists[17]) glCallList(displayLists[17]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[18]);
        if (displayLists[18]) glCallList(displayLists[18]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[19]);
        if (displayLists[19]) glCallList(displayLists[19]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[20]);
        if (displayLists[20]) glCallList(displayLists[20]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[21]);
        if (displayLists[21]) glCallList(displayLists[21]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[22]);
        if (displayLists[22]) glCallList(displayLists[22]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[23]);
        if (displayLists[23]) glCallList(displayLists[23]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[24]);
        if (displayLists[24]) glCallList(displayLists[24]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[25]);
        if (displayLists[25]) glCallList(displayLists[25]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[26]);
        if (displayLists[26]) glCallList(displayLists[26]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[27]);
        if (displayLists[27]) glCallList(displayLists[27]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[28]);
        if (displayLists[28]) glCallList(displayLists[28]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[29]);
        if (displayLists[29]) glCallList(displayLists[29]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[30]);
        if (displayLists[30]) glCallList(displayLists[30]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[31]);
        if (displayLists[31]) glCallList(displayLists[31]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[32]);
        if (displayLists[32]) glCallList(displayLists[32]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[33]);
        if (displayLists[33]) glCallList(displayLists[33]);
        while (GFX_BUSY);
        glBindTexture(GL_TEXTURE_2D, textureIDs[34]);
        if (displayLists[34]) glCallList(displayLists[34]);
        while (GFX_BUSY);
    }

    void drawBillboards(bool faceCamera, float camX, float camY, float camZ) {
        if (BILLBOARD_COUNT == 0) return;
        int  currentSlot = -1;
        bool inQuads     = false;

        for (int i = 0; i < BILLBOARD_COUNT; i++) {
            const iwatodai_dorm_floor_1_BillboardData& bb = BILLBOARDS[i];
            if (bb.texSlot != currentSlot) {
                if (inQuads) { glEnd(); inQuads = false; }
                while (GFX_BUSY);
                glBindTexture(GL_TEXTURE_2D, textureIDs[bb.texSlot]);
                currentSlot = bb.texSlot;
            }
            if (!inQuads) { glBegin(GL_QUADS); inQuads = true; }

            v16 rX = (v16)(4096), rY = 0, rZ = 0;
            v16 uX = 0, uY = (v16)(4096), uZ = 0;

            if (faceCamera) {
                float bx = (float)bb.x / 4096.0f;
                float bz = (float)bb.z / 4096.0f;
                float dx = camX - bx, dz = camZ - bz;
                float dist = sqrtf(dx*dx + dz*dz);
                if (dist > 0.001f) { dx /= dist; dz /= dist; }
                rX = (v16)(dz * 4096.0f);
                rZ = (v16)(-dx * 4096.0f);
            }

            v16 rx = mulf32(rX, bb.halfWidth),  ry = mulf32(rY, bb.halfWidth),  rz = mulf32(rZ, bb.halfWidth);
            v16 ux = mulf32(uX, bb.halfHeight), uy = mulf32(uY, bb.halfHeight), uz = mulf32(uZ, bb.halfHeight);

            glTexCoord2t16(bb.u0, bb.v1); glVertex3v16(bb.x-rx-ux, bb.y-ry-uy, bb.z-rz-uz);
            glTexCoord2t16(bb.u1, bb.v1); glVertex3v16(bb.x+rx-ux, bb.y+ry-uy, bb.z+rz-uz);
            glTexCoord2t16(bb.u1, bb.v0); glVertex3v16(bb.x+rx+ux, bb.y+ry+uy, bb.z+rz+uz);
            glTexCoord2t16(bb.u0, bb.v0); glVertex3v16(bb.x-rx+ux, bb.y-ry+uy, bb.z-rz+uz);
        }
        if (inQuads) glEnd();
    }

    void cleanup() {
        for (u32 i = 0; i < 35; i++) {
            if (displayLists[i]) { free(displayLists[i]); displayLists[i] = NULL; }
        }
        glDeleteTextures(35, textureIDs);
    }
};
