#pragma once
// Auto-generated by obj2environment.py
// Source: iwatodai_dorm.obj
// Scale: 1.272727  Centred: True
// DO NOT EDIT — regenerate from source.

#include <nds.h>
#include <stdio.h>
#include <stdlib.h>

// --- World Bounds ---
#define IWATODAI_DORM_WORLD_OFFSET_X 1.750000f
#define IWATODAI_DORM_WORLD_OFFSET_Z 1.312500f
#define IWATODAI_DORM_WORLD_WIDTH    3.500000f
#define IWATODAI_DORM_WORLD_DEPTH    2.625000f

enum iwatodai_dorm_TexSlot {
    IWATODAI_DORM_TEX_TEXTURE = 0,
    IWATODAI_DORM_TEX_COUNT = 1
};

class iwatodai_dorm_Environment {
public:
    u32* displayLists[1];
    u32 dlSizes[1];
    int textureIDs[1];

    iwatodai_dorm_Environment() {
        for (int i = 0; i < 1; i++) {
            displayLists[i] = NULL;
            dlSizes[i] = 0;
            textureIDs[i] = 0;
        }
    }

    bool load(const char* filepath, const unsigned int* bitmaps[1]) {
        FILE* file = fopen(filepath, "rb");
        if (!file) return false;

        char magic[4];
        fread(magic, 1, 4, file);
        if (magic[0] != 'E' || magic[1] != 'N' || magic[2] != 'V' || magic[3] != '1') {
            fclose(file);
            return false;
        }

        u32 groupCount;
        fread(&groupCount, sizeof(u32), 1, file);
        if (groupCount != 1) {
            fclose(file);
            return false;
        }

        for (u32 i = 0; i < groupCount; i++) {
            fread(&dlSizes[i], sizeof(u32), 1, file);
            displayLists[i] = (u32*)malloc((dlSizes[i] + 1) * sizeof(u32));
            displayLists[i][0] = dlSizes[i];
            if (dlSizes[i] > 0) {
                fread(&displayLists[i][1], sizeof(u32), dlSizes[i], file);
            }
        }
        fclose(file);

        // Bind Textures to VRAM
        if (bitmaps[0]) {
            glGenTextures(1, &textureIDs[0]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_256, TEXTURE_SIZE_256, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[0]);
        }
        return true;
    }

    void draw() {
        glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
        if (displayLists[0]) {
            glCallList(displayLists[0]);
        }
    }

    void cleanup() {
        for (u32 i = 0; i < 1; i++) {
            if (displayLists[i]) {
                free(displayLists[i]);
                displayLists[i] = NULL;
            }
        }
        glDeleteTextures(1, textureIDs);
    }
};
