#pragma once
// Auto-generated by obj2environment.py
// Source: iwatodai_streets.obj
// Scale: 0.069280  Centred: True
// DO NOT EDIT - regenerate from source.

#include <nds.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// world Bounds
#define IWATODAI_STREETS_WORLD_OFFSET_X 1.750000f
#define IWATODAI_STREETS_WORLD_OFFSET_Z 0.378843f
#define IWATODAI_STREETS_WORLD_WIDTH    3.500000f
#define IWATODAI_STREETS_WORLD_DEPTH    0.757685f

enum iwatodai_streets_TexSlot {
    IWATODAI_STREETS_TEX_F007_009_07 = 0,
    IWATODAI_STREETS_TEX_F007_009_16 = 1,
    IWATODAI_STREETS_TEX_F007_009_30 = 2,
    IWATODAI_STREETS_TEX_F007_009_25 = 3,
    IWATODAI_STREETS_TEX_F007_009_08 = 4,
    IWATODAI_STREETS_TEX_F007_009_05 = 5,
    IWATODAI_STREETS_TEX_F007_009_02 = 6,
    IWATODAI_STREETS_TEX_F007_009_04 = 7,
    IWATODAI_STREETS_TEX_F007_009_28 = 8,
    IWATODAI_STREETS_TEX_F007_009_24 = 9,
    IWATODAI_STREETS_TEX_F007_009_INFLOOR = 10,
    IWATODAI_STREETS_TEX_F007_009_09 = 11,
    IWATODAI_STREETS_TEX_F007_009_11 = 12,
    IWATODAI_STREETS_TEX_F007_009_10 = 13,
    IWATODAI_STREETS_TEX_F007_009_13 = 14,
    IWATODAI_STREETS_TEX_F007_009_12 = 15,
    IWATODAI_STREETS_TEX_F007_009_17 = 16,
    IWATODAI_STREETS_TEX_F007_009_18 = 17,
    IWATODAI_STREETS_TEX_F007_009_32 = 18,
    IWATODAI_STREETS_TEX_F007_009_33 = 19,
    IWATODAI_STREETS_TEX_F007_009_29 = 20,
    IWATODAI_STREETS_TEX_F007_009_27 = 21,
    IWATODAI_STREETS_TEX_F007_009_22 = 22,
    IWATODAI_STREETS_TEX_F007_009_03 = 23,
    IWATODAI_STREETS_TEX_F007_009_WOOD01 = 24,
    IWATODAI_STREETS_TEX_COUNT = 25
};

struct iwatodai_streets_BillboardData {
    v16 x, y, z;
    v16 halfWidth, halfHeight;
    int texSlot;
    short u0, v0, u1, v1;
};

class iwatodai_streets_Environment {
public:
    u32* displayLists[25];
    u32 dlSizes[25];
    int textureIDs[25];

    static const int BILLBOARD_COUNT = 0;
    const iwatodai_streets_BillboardData* BILLBOARDS = NULL;

    iwatodai_streets_Environment() {
        for (int i = 0; i < 25; i++) {
            displayLists[i] = NULL; dlSizes[i] = 0; textureIDs[i] = 0;
        }
    }

    bool load(const char* filepath, const unsigned int* bitmaps[25]) {
        FILE* file = fopen(filepath, "rb");
        if (!file) return false;

        char magic[4];
        fread(magic, 1, 4, file);
        if (magic[0] != 'E' || magic[1] != 'N' || magic[2] != 'V' || magic[3] != '1') {
            fclose(file); return false;
        }

        u32 groupCount;
        fread(&groupCount, sizeof(u32), 1, file);
        if (groupCount != 25) { fclose(file); return false; }

        for (u32 i = 0; i < groupCount; i++) {
            fread(&dlSizes[i], sizeof(u32), 1, file);
            displayLists[i] = (u32*)malloc((dlSizes[i] + 1) * sizeof(u32));
            displayLists[i][0] = dlSizes[i];
            if (dlSizes[i] > 0) fread(&displayLists[i][1], sizeof(u32), dlSizes[i], file);
        }
        fclose(file);

        if (bitmaps[0]) {
            glGenTextures(1, &textureIDs[0]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[0]);
        }
        if (bitmaps[1]) {
            glGenTextures(1, &textureIDs[1]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[1]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[1]);
        }
        if (bitmaps[2]) {
            glGenTextures(1, &textureIDs[2]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[2]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_256, TEXTURE_SIZE_256, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[2]);
        }
        if (bitmaps[3]) {
            glGenTextures(1, &textureIDs[3]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[3]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[3]);
        }
        if (bitmaps[4]) {
            glGenTextures(1, &textureIDs[4]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[4]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[4]);
        }
        if (bitmaps[5]) {
            glGenTextures(1, &textureIDs[5]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[5]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[5]);
        }
        if (bitmaps[6]) {
            glGenTextures(1, &textureIDs[6]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[6]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[6]);
        }
        if (bitmaps[7]) {
            glGenTextures(1, &textureIDs[7]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[7]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_256, TEXTURE_SIZE_256, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[7]);
        }
        if (bitmaps[8]) {
            glGenTextures(1, &textureIDs[8]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[8]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_256, TEXTURE_SIZE_256, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[8]);
        }
        if (bitmaps[9]) {
            glGenTextures(1, &textureIDs[9]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[9]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[9]);
        }
        if (bitmaps[10]) {
            glGenTextures(1, &textureIDs[10]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[10]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[10]);
        }
        if (bitmaps[11]) {
            glGenTextures(1, &textureIDs[11]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[11]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[11]);
        }
        if (bitmaps[12]) {
            glGenTextures(1, &textureIDs[12]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[12]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[12]);
        }
        if (bitmaps[13]) {
            glGenTextures(1, &textureIDs[13]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[13]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[13]);
        }
        if (bitmaps[14]) {
            glGenTextures(1, &textureIDs[14]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[14]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[14]);
        }
        if (bitmaps[15]) {
            glGenTextures(1, &textureIDs[15]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[15]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[15]);
        }
        if (bitmaps[16]) {
            glGenTextures(1, &textureIDs[16]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[16]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[16]);
        }
        if (bitmaps[17]) {
            glGenTextures(1, &textureIDs[17]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[17]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[17]);
        }
        if (bitmaps[18]) {
            glGenTextures(1, &textureIDs[18]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[18]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_64, TEXTURE_SIZE_64, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[18]);
        }
        if (bitmaps[19]) {
            glGenTextures(1, &textureIDs[19]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[19]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_32, TEXTURE_SIZE_32, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[19]);
        }
        if (bitmaps[20]) {
            glGenTextures(1, &textureIDs[20]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[20]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_64, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[20]);
        }
        if (bitmaps[21]) {
            glGenTextures(1, &textureIDs[21]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[21]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[21]);
        }
        if (bitmaps[22]) {
            glGenTextures(1, &textureIDs[22]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[22]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[22]);
        }
        if (bitmaps[23]) {
            glGenTextures(1, &textureIDs[23]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[23]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_128, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[23]);
        }
        if (bitmaps[24]) {
            glGenTextures(1, &textureIDs[24]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[24]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_256, TEXTURE_SIZE_128, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[24]);
        }
        return true;
    }

    void draw() {
        glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
        if (displayLists[0]) glCallList(displayLists[0]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[1]);
        if (displayLists[1]) glCallList(displayLists[1]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[2]);
        if (displayLists[2]) glCallList(displayLists[2]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[3]);
        if (displayLists[3]) glCallList(displayLists[3]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[4]);
        if (displayLists[4]) glCallList(displayLists[4]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[5]);
        if (displayLists[5]) glCallList(displayLists[5]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[6]);
        if (displayLists[6]) glCallList(displayLists[6]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[7]);
        if (displayLists[7]) glCallList(displayLists[7]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[8]);
        if (displayLists[8]) glCallList(displayLists[8]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[9]);
        if (displayLists[9]) glCallList(displayLists[9]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[10]);
        if (displayLists[10]) glCallList(displayLists[10]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[11]);
        if (displayLists[11]) glCallList(displayLists[11]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[12]);
        if (displayLists[12]) glCallList(displayLists[12]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[13]);
        if (displayLists[13]) glCallList(displayLists[13]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[14]);
        if (displayLists[14]) glCallList(displayLists[14]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[15]);
        if (displayLists[15]) glCallList(displayLists[15]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[16]);
        if (displayLists[16]) glCallList(displayLists[16]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[17]);
        if (displayLists[17]) glCallList(displayLists[17]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[18]);
        if (displayLists[18]) glCallList(displayLists[18]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[19]);
        if (displayLists[19]) glCallList(displayLists[19]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[20]);
        if (displayLists[20]) glCallList(displayLists[20]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[21]);
        if (displayLists[21]) glCallList(displayLists[21]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[22]);
        if (displayLists[22]) glCallList(displayLists[22]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[23]);
        if (displayLists[23]) glCallList(displayLists[23]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[24]);
        if (displayLists[24]) glCallList(displayLists[24]);
    }

    void drawBillboards(bool faceCamera, float camX, float camY, float camZ) {
        if (BILLBOARD_COUNT == 0) return;
        int currentSlot = -1;
        bool inQuads = false;

        for (int i = 0; i < BILLBOARD_COUNT; i++) {
            const iwatodai_streets_BillboardData& bb = BILLBOARDS[i];
            if (bb.texSlot != currentSlot) {
                if (inQuads) { glEnd(); inQuads = false; }
                glBindTexture(GL_TEXTURE_2D, textureIDs[bb.texSlot]);
                currentSlot = bb.texSlot;
            }
            if (!inQuads) { glBegin(GL_QUADS); inQuads = true; }

            v16 rX = (v16)(4096), rY = 0, rZ = 0;
            v16 uX = 0, uY = (v16)(4096), uZ = 0;

            if (faceCamera) {
                float bx = (float)bb.x / 4096.0f;
                float bz = (float)bb.z / 4096.0f;
                float dx = camX - bx;
                float dz = camZ - bz;
                float dist = sqrt(dx*dx + dz*dz);
                if (dist > 0.001f) { dx /= dist; dz /= dist; }
                rX = (v16)(dz * 4096.0f);
                rZ = (v16)(-dx * 4096.0f);
            }

            v16 rx = mulf32(rX, bb.halfWidth);
            v16 ry = mulf32(rY, bb.halfWidth);
            v16 rz = mulf32(rZ, bb.halfWidth);
            v16 ux = mulf32(uX, bb.halfHeight);
            v16 uy = mulf32(uY, bb.halfHeight);
            v16 uz = mulf32(uZ, bb.halfHeight);

            glTexCoord2t16(bb.u0, bb.v1);
            glVertex3v16(bb.x - rx - ux, bb.y - ry - uy, bb.z - rz - uz);
            glTexCoord2t16(bb.u1, bb.v1);
            glVertex3v16(bb.x + rx - ux, bb.y + ry - uy, bb.z + rz - uz);
            glTexCoord2t16(bb.u1, bb.v0);
            glVertex3v16(bb.x + rx + ux, bb.y + ry + uy, bb.z + rz + uz);
            glTexCoord2t16(bb.u0, bb.v0);
            glVertex3v16(bb.x - rx + ux, bb.y - ry + uy, bb.z - rz + uz);
        }
        if (inQuads) glEnd();
    }

    void cleanup() {
        for (u32 i = 0; i < 25; i++) {
            if (displayLists[i]) { free(displayLists[i]); displayLists[i] = NULL; }
        }
        glDeleteTextures(25, textureIDs);
    }
};
