#pragma once
// Auto-generated by dialogue_compiler.py
// Scene: demo

#include "controllers/DialogueController.h"

extern int demo_dialogue_bg_slot;

void  demo_unload();

// ── interaction: yuki_guard_argument — Yuki arguing with a guard at the gate
extern const char* demo_yuki_guard_argument_bg_names[4];
extern void        (*demo_yuki_guard_argument_bg_loaders[4])();
void  demo_yuki_guard_argument_load_bg(int bgIndex);
extern dialogue demo_yuki_guard_argument_lines[18];
void  demo_yuki_guard_argument_init();
void  demo_yuki_guard_argument_load();
inline dialogue* demo_yuki_guard_argument_first() { return &demo_yuki_guard_argument_lines[0]; }
inline dialogue* demo_yuki_guard_argument_vouch() { return &demo_yuki_guard_argument_lines[7]; }
inline dialogue* demo_yuki_guard_argument_side_guard() { return &demo_yuki_guard_argument_lines[12]; }
inline dialogue* demo_yuki_guard_argument_stay_out() { return &demo_yuki_guard_argument_lines[15]; }

inline void demo_init_all() {
    demo_yuki_guard_argument_init();
}
